theme: fluid

deploy:
  type: git
  repo: git@github.com:XiannaWeng/xiannaweng.github.io.git
  branch: main

author: Wenger

updated_option: 'mtime'

url: https://wengerblogs.me

title: Wenger's Blog
description: 'The best way to predict future is to code it'